version: '3.8'

services:
  orion-cv:
    image: ${DOCKERHUB_USERNAME:-votre-pseudo-dockerhub}/orion-cv:latest
    container_name: orion-cv
    restart: unless-stopped
    ports:
      - "8086:80"
    # Si vous utilisez un reverse proxy (Traefik, Nginx Proxy Manager), vous pouvez utiliser des labels ou réseaux ici.
    # réseaux:
    #   - web

    # networks:
    #   web:
    #     external: true
