name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy-to-digitalocean:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Liste des fichiers et dossiers à copier sur le serveur
          source: "index.html,assets,img"
          # Le chemin de destination sur votre serveur (à adapter selon votre configuration web, par ex. /var/www/html/cv)
          target: "/var/www/cv-horion"
          # Permet de vider le dossier de destination avant de copier
          rm: true
